<form action="<?php echo 'register/adduser';?>" method="post">

    <table>

        <tr>

            <td><label for="login">Nom d'utilisateur :</label></td>
            <td><input type="text" name="login" id="login"/></td>

        </tr>

        <tr>

            <td><label for="pass">Mot de passe :</label></td>
            <td><input type="password" name="pass" id="pass"/></td>

        </tr>

        <tr>

            <td><label for="type">Vous êtes :</label></td>
            <td><input type="radio" name="type" id="type" value="User"/>Utilisateur</td>
            <td><input type="radio" name="type" id="type" value="Admin"/>Administrateur</td>

        </tr>

    </table>

    <input type="submit" name="register" value="S'inscrire"/>

</form>
