<form action="<?php echo 'register/adduser';?>" method="post">

    <table>

        <tr>

            <td><label for="login">Username :</label></td>
            <td><input type="text" name="login" id="login"/></td>

        </tr>

        <tr>

            <td><label for="pass">Mot de passe :</label></td>
            <td><input type="password" name="pass" id="pass"/></td>

        </tr>

    </table>

    <input type="submit" name="register" value="Register"/>

</form>
