<?php

$form = $this->form;
$form->setAttribute('action', $this->url(
    'login/process',
    array(
        'action'     => 'authenticate',
    )
));
$form->prepare();


echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
echo "<a href =\"./register\">S'inscrire maintenant</a>";
if ($this->messages){
    echo '<ul>';
    foreach($this->messages as $message)
    {
        echo '<li>'.$message.'</li>';


    }

    echo '</ul>';

}