<h1>Add a new community</h1>
<form action="<?php echo $this->url('community', array('action' => 'add'));?>" method="post">

    <table>

        <tr>

            <td><label for="name">Name :</label></td>
            <td><input type="text" name="name" id="name"/></td>

        </tr>

        <tr>

            <td><label for="desc">Description :</label></td>
           <td> <textarea rows="4" cols="100" name="desc" id="desc""></textarea> </td>

        </tr>

    </table>

    <input type="submit" name="add_Community" value="Add community"/>

</form>