<?php
    use Application\Model\DbAdapterConfig;
    use Zend\Db\Sql\Sql;
    use Zend\Db\Adapter\Adapter;
?>
<h1><?php echo $this->community[0]['name_Community']; ?></h1>
<p><?php echo $this->community[0]['description_Community']; ?></p>
<h2>Liste des commentaires :</h2>
<?php
if (count($this->comments) == 0)
{
    echo 'Aucun commentaire';
}
else
{
    foreach ($this->comments as $comment)
    {
        echo '<p>' . $comment['description_comment'] . ' [ <span style="font-weight:bold;">' . $comment['login'] . '</span> ]</p>';
    }
}
?>

    <form action="<?php echo $this->url('community', array('action' => 'addComment'))?>" method="post">
        <label for="comment">Ajouter un commentaire sur la communauté :</label>
        <textarea name="comment" id="comment"> </textarea>
        <?php echo "<input type=\"hidden\" name=\"idCommunity\" value=\"" . $this->community[0]['id_Community'] . "\"/>"; ?>
        <br/>
        <input type="submit" value="Valider"/>

    </form>

<hr/>
<?php
    echo "<h2>Liste des idées</h2>";
    if (count($this->ideas) == 0)
    {
        echo 'Aucune idée';
    }
    else
    {
        $dbAdapter = new Adapter(DbAdapterConfig::getDbAdapter());
        $sql = new Sql($dbAdapter);

        foreach ($this->ideas as $idea)
        {
            echo '<p>' . $idea['title_idea'] . ' : ' . $idea['text_idea'] . '</p>';

            // Récupération de tous les commentaires associé à cette idée
            $select = $sql->select();
            $select->from('comment')
                ->where('id_idea = ' . $idea['id_idea']);

            $result = $sql->prepareStatementForSqlObject($select)->execute();
            foreach ($result as $row)
            {
                echo "- " . $row['description_comment'];
            }
            ?>

            <form action="<?php echo 'community/addIdeaComment';?>" method="post">
                <label for="comentIdea">ajouter un commentaire sur cette idée :</label>
                <textarea name="commentIdea" id="commentIdea"> </textarea>
                <?php echo "<input type=\"hidden\" name=\"idIdea\" value=\"" . $idea['id_idea'] . "\"/>"; ?>
                <br/>
                <input type="submit" value="Valider"/>
            </form>
<?php
        }
?>
        <form action="<?php echo 'community/addIdea';?>" method="post">
<label for="idea">proposer une idée à la communauté :</label>
<textarea name="idea" id="idea"> </textarea>
                    <?php echo "<input type=\"hidden\" name=\"idCommunity\" value=\"" . $this->community[0]['id_Community'] . "\"/>"; ?>

<br/>
            <input type="submit" value="Valider"/>

        </form>
<?php
    }
?>