<h1>Communautés</h1>
<table class="table">
    <tr>
        <th>Nom</th>
        <th>Description</th>
    </tr>
    <?php foreach ($this->communities as $community) : ?>
        <tr>
            <td><a href="<?php echo $this->url('community', array('action'=>'index', 'id' => $community['id_Community']));?>"><?php echo $community['name_Community']; ?></a></td>
            <td><?php echo $community['description_Community'];?></td>
        </tr>
    <?php endforeach; ?>
</table>
<?php
if ($this->logged)
{
?>
    <a href="<?php echo $this->url('community', array('action' => 'add'));?>">Ajouter communauté</a>
<?php
}
?>

<br>

<h1>Idées</h1>
<table class="table">
    <tr>
        <th>Titre</th>
        <th>Description</th>
        <th>Communauté</th>
        <th>Auteur</th>
    </tr>
    <?php foreach ($this->ideas as $idea) : ?>
        <tr>
            <td><?php echo $idea['title_idea'];?></td>
            <td><?php echo $idea['text_idea'];?></td>
            <td><a href="<?php echo $this->url('community', array('action'=>'index', 'id' => $idea['id_Community']));?>"><?php echo $idea['name_Community']; ?></a></td>
            <td><?php echo $idea['login'];?></td>
        </tr>
    <?php endforeach; ?>

</table>
<?php
if ($this->logged)
{
?>
<a href="<?php echo $this->url('idea', array('action'=>'add'));?>">Ajouter idée</a>
<?php
}
?>
