<h1>Communities</h1>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Description</th>
    </tr>
    <?php foreach ($this->communities as $community) : ?>
        <tr>
            <td><a href="<?php echo $this->url('community', array('action'=>'index', 'id' => $community['id_Community']));?>"><?php echo $community['name_Community']; ?></a></td>
            <td><?php echo $community['description_Community'];?></td>
        </tr>
    <?php endforeach; ?>
</table>
<a href="<?php echo $this->url('community', array('action'=>'add'));?>"> Add Community </a>

<br>

<h1>Ideas</h1>
<table class="table">
    <tr>
        <th>Title</th>
        <th>Text</th>
        <th>Author</th>
    </tr>
    <?php foreach ($this->ideas as $idea) : ?>
        <tr>
            <td><?php echo $idea['title_idea'];?></td>
            <td><?php echo $idea['text_idea'];?></td>
            <td><?php echo $idea['login'];?></td>
        </tr>
    <?php endforeach; ?>

</table>

<a href="<?php echo $this->url('idea', array('action'=>'add'));?>"> Add Idea </a>