<h1>Communities</h1>

<table class="table">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Description</th>
    </tr>
    <?php foreach ($communities as $community) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($community->id);?></td>
            <td><?php echo $this->escapeHtml($community->name);?></td>
            <td><?php echo $this->escapeHtml($community->description);?></td>
        </tr>
    <?php endforeach; ?>
</table>

<br>

<h1>Ideas</h1>